---
all:
  children:
    servers:
      hosts:
        172.31.29.75:
          packages:
            - git
            - nano
            - tree
            - net-tools
      vars:
        group: name
        