---
- name: lamp stack installation on ubuntu
  hosts: all
  become: yes
  tasks:
    - name: install apache2
      ansible.builtin.apt:
        name: apache2
        update-cache: yes
        state: present
    - name: install php
      ansible.builtin.apt:
        name:
          - php
          - libapache2-mod-php
        state: present
    - name: reload apache2 service
      ansible.builtin.systemd_service:
        name: apache2.service
        state: reloaded
    - name: add info.php file
      ansible.builtin.copy:
        src: info.php
        dest: /var/www/html/info.php