---
- name: install utilities
  hosts: all
  become: yes
  vars:
    util:
      - git
      - nano
      - tree
  tasks:
    - name: install utilities
      ansible.builtin.apt:
        name: "{{ util }}"
        update_cache: yes
        state: present
      notify:
        - ensure ssh running
  handlers:
    - name: ensure ssh running
      ansible.builtin.systemd_service:
        name: sshd
        state: started