---
- name: tomcat 10 installation on ubuntu 2204
  hosts: all
  become: yes
  vars:
    java_name: openjdk-11-jdk
    user_name: tomcat
    group_name: tomcat
    user_home: /opt/tomcat
    user_shell: /bin/false
    tomcat_version: "10.1.17"
    tomcat_major_version: "10"
    tomcat_service_name: tomcat.service
  tasks:
    - name: install java
      ansible.builtin.apt:
        name: "{{ java_name }}"
        update_cache: yes
        state: present
    - name: create group
      ansible.builtin.group:
        name: "{{ group_name }}"
        state: present
    - name: create user
      ansible.builtin.user:
        name: "{{ user_name }}"
        create_home: yes
        group: "{{ group_name }}"
        home: "{{ user_home }}"
        shell: "{{ user_shell }}"
        state: present
    - name: download and extract tomcat
      ansible.builtin.unarchive:
        src: "https://www-eu.apache.org/dist/tomcat/tomcat-{{ tomcat_major_version }}/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
        remote_src: yes
        dest: "{{ user_home }}"
    - name: create symbolic link
      ansible.builtin.file:
        src: "{{ user_home }}/apache-tomcat-{{ tomcat_version }}"
        path: "{{ user_home }}/latest"
        state: link
    - name: change ownership
      ansible.builtin.file:
        path: "{{ user_home }}"
        owner: "{{ user_name }}"
        group: "{{ group_name }}"
        recurse: yes
    - name: provide executable permissions to shell script
      ansible.builtin.command: "sudo sh -c 'chmod +x {{ user_home }}/latest/bin/*.sh'"
    - name: create systemd unit file
      ansible.builtin.copy:
        src: "{{ tomcat_service_name }}"
        dest: "/etc/systemd/system/{{ tomcat_service_name }}"
        owner: "{{ user_name }}"
        group: "{{ group_name }}"
    - name: do system daemon-reload, enable and start tomcat
      ansible.builtin.systemd_service:
        name: "{{ tomcat_service_name }}"
        daemon-reload: yes
        enabled: yes
        state: started
    - name: copy the tomcat users
      ansible.builtin.copy:
        src: tomcat-users.xml
        dest: "{{ user_home }}/latest/conf/tomcat-users.xml"
        owner: "{{ user_name }}"
        group: "{{ group_name }}"
    - name: copy the manager context
      ansible.builtin.copy:
        src: manager-context.xml
        dest: "{{ user_home }}/latest/webapps/manager/META-INF/context.xml"
        owner: "{{ user_name }}"
        group: "{{ group_name }}"
    - name: copy the hostmanager context
      ansible.builtin.copy:
        src: hostmanager-context.xml
        dest: "{{ user_home }}/latest/webapps/host-manager/META-INF/context.xml"
        owner: "{{ user_name }}"
        group: "{{ group_name }}"
    - name: restart the tomcat
      ansible.builtin.systemd_service:
        name: "{{ tomcat_service_name }}"
        state: restarted