---
- name: tomcat 10 installation on ubuntu 2204
  hosts: all
  become: yes
  tasks:
    - name: install java 11
      ansible.builtin.apt:
        name: openjdk-11-jdk
        update_cache: yes
        state: present
    - name: create tomcat user
      ansible.builtin.user:
        name: tomcat
        create_home: yes
        group: tomcat
        home: /opt/tomcat
        shell: /bin/false