---
- name: tomcat 10 installation on ubuntu 2204
  hosts: all
  become: yes
  tasks:
    - name: install java 11
      ansible.builtin.apt:
        name: openjdk-11-jdk
        update_cache: yes
        state: present
    - name: create tomcat group
      ansible.builtin.group:
        name: tomcat
        state: present
    - name: create tomcat user
      ansible.builtin.user:
        name: tomcat
        create_home: yes
        group: tomcat
        home: /opt/tomcat
        shell: /bin/false
        state: present
    - name: download and extract tomcat
      ansible.builtin.unarchive:
        src: https://www-eu.apache.org/dist/tomcat/tomcat-10/v10.1.17/bin/apache-tomcat-10.1.17.tar.gz
        remote_src: yes
        dest: /opt/tomcat/
    - name: create symbolic link
      ansible.builtin.file:
        src: /opt/tomcat/apache-tomcat-10.1.17
        path: /opt/tomcat/latest
        state: link